version: '3.8'

services:
  # 数据库服务
  db:
    image: mysql:8.0
    container_name: rice-platform-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rice_platform
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - rice-platform-network

  # 后端服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
    container_name: rice-platform-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=docker
    env_file:
      - ./backend/.env.docker
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - rice-platform-network
    depends_on:
      - db

  # 前端服务
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    container_name: rice-platform-frontend
    restart: unless-stopped
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    networks:
      - rice-platform-network
    depends_on:
      - backend

networks:
  rice-platform-network:
    driver: bridge

volumes:
  mysql_data: